# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6cc494a3ae287dfbccbae505f2c6c937282d9e7c18ad84126292068c901bbd84ed52706ce6f4cb38ce2b637c092f6ebc651d4036395720e6a9725683fac1e25

test:
  secret_key_base: 5ce19fe72a5da21785f644e374f0ceb595ee40efde3a44d22314a75882330f461c32220288eb18144059a9d71949c55770797f078cfee671c35a33284e8ba1eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
